source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'rake', '0.8.7'
gem 'warden','0.10.7'
gem 'devise','1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client'
gem 'mechanize'
gem 'mysql2','0.2.18'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate'
gem 'sqlite3'
gem 'rcov','1.0.0'
